# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 478)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/dlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 271, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 381, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 230, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 300, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 330, 81, 16))
        self.label_10.setObjectName("label_10")
        self.server_id = QtWidgets.QLabel(self.centralwidget)
        self.server_id.setGeometry(QtCore.QRect(90, 80, 311, 16))
        self.server_id.setObjectName("server_id")
        self.server_name = QtWidgets.QLabel(self.centralwidget)
        self.server_name.setGeometry(QtCore.QRect(100, 110, 291, 16))
        self.server_name.setObjectName("server_name")
        self.server_veri_level = QtWidgets.QLabel(self.centralwidget)
        self.server_veri_level.setGeometry(QtCore.QRect(160, 140, 241, 16))
        self.server_veri_level.setObjectName("server_veri_level")
        self.nsfw_level = QtWidgets.QLabel(self.centralwidget)
        self.nsfw_level.setGeometry(QtCore.QRect(130, 170, 261, 16))
        self.nsfw_level.setObjectName("nsfw_level")
        self.server_vanity = QtWidgets.QLabel(self.centralwidget)
        self.server_vanity.setGeometry(QtCore.QRect(120, 200, 271, 16))
        self.server_vanity.setObjectName("server_vanity")
        self.server_welcome_msg = QtWidgets.QLabel(self.centralwidget)
        self.server_welcome_msg.setGeometry(QtCore.QRect(160, 230, 241, 16))
        self.server_welcome_msg.setObjectName("server_welcome_msg")
        self.inviter = QtWidgets.QLabel(self.centralwidget)
        self.inviter.setGeometry(QtCore.QRect(70, 270, 321, 16))
        self.inviter.setObjectName("inviter")
        self.inviter_id = QtWidgets.QLabel(self.centralwidget)
        self.inviter_id.setGeometry(QtCore.QRect(80, 300, 311, 16))
        self.inviter_id.setObjectName("inviter_id")
        self.inviter_avatar = QtWidgets.QLabel(self.centralwidget)
        self.inviter_avatar.setGeometry(QtCore.QRect(100, 330, 301, 16))
        self.inviter_avatar.setObjectName("inviter_avatar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discord Invite Recon"))
        self.label.setText(_translate("MainWindow", "Discord Invite Link"))
        self.pushButton.setText(_translate("MainWindow", "Start Recon"))
        self.label_2.setText(_translate("MainWindow", "Server ID:"))
        self.label_3.setText(_translate("MainWindow", "Server Name:"))
        self.label_4.setText(_translate("MainWindow", "Server Verification Level:"))
        self.label_5.setText(_translate("MainWindow", "Server NSFW Level:"))
        self.label_6.setText(_translate("MainWindow", "Server Vanity Link:"))
        self.label_7.setText(_translate("MainWindow", "Server Welcome Message:"))
        self.label_8.setText(_translate("MainWindow", "Inviter:"))
        self.label_9.setText(_translate("MainWindow", "Inviter ID:"))
        self.label_10.setText(_translate("MainWindow", "Inviter Avatar:"))
        self.server_id.setText(_translate("MainWindow", "TextLabel"))
        self.server_name.setText(_translate("MainWindow", "TextLabel"))
        self.server_veri_level.setText(_translate("MainWindow", "TextLabel"))
        self.nsfw_level.setText(_translate("MainWindow", "TextLabel"))
        self.server_vanity.setText(_translate("MainWindow", "TextLabel"))
        self.server_welcome_msg.setText(_translate("MainWindow", "TextLabel"))
        self.inviter.setText(_translate("MainWindow", "TextLabel"))
        self.inviter_id.setText(_translate("MainWindow", "TextLabel"))
        self.inviter_avatar.setText(_translate("MainWindow", "TextLabel"))

